version: '3.5'

services:
  article.api:
    image: ${DOCKER_REGISTRY-}articleapi
    build:
      context: .
      dockerfile: src/services/Article/Article.Api/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/services/Identity/Identity.Api/Dockerfile

  files.api:
    image: ${DOCKER_REGISTRY-}filesapi
    build:
      context: .
      dockerfile: src/services/Files/Files.Api/Dockerfile

  admin.gateway:
    image: ${DOCKER_REGISTRY-}admingateway
    build:
      context: .
      dockerfile: src/api-gateways/AdminGateway/Dockerfile

  spa.aggregator:
    image: ${DOCKER_REGISTRY-}spaaggregator
    build:
      context: .
      dockerfile: src/api-gateways/SpaAggregator/Dockerfile
